[book]
title = "Kubernetes CSI Documentation"
description = "CSI support for Kubernetes"
authors = ["Luis Pabón", "Contributions from the Kubernetes and CSI Community"]

[build]
build-dir = "../docs"
